# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems: [jekyll-paginate]


# Permalinks
permalink:        pretty

# Setup
title:            Dave Goodman
tagline:          'Hello from Edinburgh'
description:      'Irregular meanderings on writing, the outdoors and the odd spot of obscure marginalia.' 
url:              http://www.davidgoodman.net
baseurl:          /

author:
  name:           'Dave Goodman'
  url:            https://twitter.com/davegoodman

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           
